from django.urls import path
from .views import HomeView, RegistroChamadaView, RegistroChamadaReactView, CustomPasswordChangeView
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomLoginView
from . import views_simple

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('', HomeView.as_view(), name='home'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('registro-chamada/', RegistroChamadaView.as_view(), name='registro_chamada'),
    path('registro-chamada-react/', RegistroChamadaReactView.as_view(), name='registro_chamada_react'),
    path('unidades-saude/', views.unidades_saude, name='unidades_saude'),
    path('unidades-saude/criar/', views.criar_unidade, name='criar_unidade'),
    path('unidades-saude/<int:pk>/editar/', views.editar_unidade, name='editar_unidade'),
    path('unidades-saude/<int:pk>/visualizar/', views.visualizar_unidade, name='visualizar_unidade'),
    path('unidades-saude/<int:pk>/excluir/', views.excluir_unidade, name='excluir_unidade'),
    path('unidades-saude/export-pdf/', views.export_unidades_pdf, name='export_unidades_pdf'),
    path('unidades-saude/export-excel/', views.export_unidades_excel, name='export_unidades_excel'),
    path('unidades-saude/export-csv/', views.export_unidades_csv, name='export_unidades_csv'),
    path('api/cnes/<str:codigo_cnes>/', views.consultar_cnes_api, name='consultar_cnes_api'),
    path('api/unidade-saude/', views.consultar_unidade_saude_api, name='consultar_unidade_saude_api'),
    path('historico/', views.historico_chamadas, name='historico_chamadas'),
    path('historico/export-pdf/', views.export_historico_pdf_simples, name='export_historico_pdf'),
    path('historico/export-excel/', views.export_historico_excel, name='export_historico_excel'),
    path('historico/export-csv/', views.export_historico_csv, name='export_historico_csv'),
    path('chamada/<int:chamada_id>/detalhes/', views.visualizar_detalhes_chamada, name='visualizar_detalhes_chamada'),
    path('chamada/<int:chamada_id>/editar-form/', views.editar_chamada_form, name='editar_chamada_form'),
    path('api/editar-chamada/', views.editar_chamada_api, name='editar_chamada_api'),
    path('configuracoes/', views.configuracoes, name='configuracoes'),
    path('configuracoes/manual/', views.manual_sistema, name='manual_sistema'),
    path('configuracoes/perfil/', views.editar_perfil, name='editar_perfil'),
    path('configuracoes/perfil/<int:user_id>/', views.editar_perfil, name='editar_perfil_usuario'),
    path('configuracoes/senha/', CustomPasswordChangeView.as_view(), name='alterar_senha'),
    path('configuracoes/notificacoes/', views.notificacoes, name='notificacoes'),
    path('usuarios/criar/', views.criar_usuario, name='criar_usuario'),
    path('usuarios/gerenciar/', views.gerenciar_usuarios, name='gerenciar_usuarios'),
    path('usuarios/<int:user_id>/detalhes/', views.detalhes_usuario, name='detalhes_usuario'),
    path('usuarios/<int:user_id>/editar/', views.editar_usuario, name='editar_usuario'),
    path('usuarios/<int:user_id>/desativar/', views.desativar_usuario, name='desativar_usuario'),
    path('usuarios/<int:user_id>/excluir/', views.excluir_usuario, name='excluir_usuario'),
    path('api/excluir-usuario/', views.api_excluir_usuario, name='api_excluir_usuario'),
    path('usuarios/export-pdf/', views.export_usuarios_pdf, name='export_usuarios_pdf'),
    path('usuarios/export-excel/', views.export_usuarios_excel, name='export_usuarios_excel'),
    path('usuarios/export-csv/', views.export_usuarios_csv, name='export_usuarios_csv'),
    path('api/estatisticas-usuarios/', views.api_estatisticas_usuarios, name='api_estatisticas_usuarios'),
    path('sistema/backup/', views.backup_sistema, name='backup_sistema'),
    path('sistema/relatorios/', views.relatorios_sistema, name='relatorios_sistema'),
    # Rotas de exportação de relatórios
    path('sistema/relatorios/usuarios-mes/export-excel/', views.export_relatorio_usuarios_mes_excel, name='export_relatorio_usuarios_mes_excel'),
    path('sistema/relatorios/usuarios-mes/export-csv/', views.export_relatorio_usuarios_mes_csv, name='export_relatorio_usuarios_mes_csv'),
    path('sistema/relatorios/usuarios-mes/export-pdf/', views.export_relatorio_usuarios_mes_pdf, name='export_relatorio_usuarios_mes_pdf'),
    path('sistema/relatorios/export-excel/', views.export_relatorio_geral_excel, name='export_relatorio_geral_excel'),
    path('sistema/relatorios/export-csv/', views.export_relatorio_geral_csv, name='export_relatorio_geral_csv'),
    path('sistema/relatorios/export-pdf/', views.export_relatorio_geral_pdf, name='export_relatorio_geral_pdf'),
    path('upload-avatar/', views.upload_avatar, name='upload_avatar'),
    path('remove-avatar/', views.remove_avatar, name='remove_avatar'),
    path('lista-telefonica/', views.lista_telefonica, name='lista_telefonica'),
    path('api/lista-telefonica/', views.api_lista_telefonica, name='api_lista_telefonica'),
    path('test-react/', views.test_react_view, name='test_react'),
    path('debug-console/', views.debug_console_view, name='debug_console'),
    path('test-react-validation/', views.test_react_validation_view, name='test_react_validation'),
    path('home-simple/', views_simple.home_react_super_simple, name='home_react_super_simple'),
    path('test-basic-react/', views_simple.test_basic_react, name='test_basic_react'),
    path('home-working/', views_simple.home_react_working, name='home_react_working'),
    path('home-debug/', views.home_debug_view, name='home_debug'),
    path('debug-numeros-reais/', views.debug_numeros_reais, name='debug_numeros_reais'),
] 