# Generated by Django 5.2.3 on 2025-06-22 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_chamada', models.CharField(choices=[('emergencia', 'Emergência'), ('consulta', 'Consulta'), ('informacao', 'Informação'), ('reclamacao', 'Reclamação'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('chamada_recebida', 'Chamada Recebida'), ('chamada_efetuada', 'Chamada Efetuada')], max_length=20)),
                ('nome_atendente', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario_criador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Chamada',
                'verbose_name_plural': 'Registros de Chamadas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
