# Generated by Django 5.2.3 on 2025-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unidadesaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='unidadesaude',
            name='tipo',
            field=models.CharField(choices=[('UBS', 'Unidade Básica de Saúde'), ('HOSPITAL', 'Hospital'), ('POSTO', 'Posto de Saúde'), ('UPA', 'Unidade de Pronto Atendimento'), ('CAPS', 'Centro de Atenção Psicossocial'), ('OUTROS', 'Outros')], default='UBS', max_length=20),
        ),
    ]
