# Generated by Django 5.2.3 on 2025-06-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unidadesaude_responsavel_unidadesaude_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesaude',
            name='tipo',
            field=models.CharField(choices=[('UNIDADE_EXECUTANTE', 'Unidade Executante'), ('UNIDADE_SOLICITANTE', 'Unidade Solicitante'), ('EXECUTANTE_SOLICITANTE', 'Executante/Solicitante'), ('UBS', 'Unidade Básica de Saúde'), ('HOSPITAL', 'Hospital'), ('POSTO', 'Posto de Saúde'), ('UPA', 'Unidade de Pronto Atendimento'), ('CAPS', 'Centro de Atenção Psicossocial'), ('OUTROS', 'Outros')], default='UBS', max_length=25),
        ),
    ]
