# Generated by Django 5.2.3 on 2025-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_unidadesaude_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesaude',
            name='tipo',
            field=models.CharField(choices=[('UNIDADE_EXECUTANTE', 'Unidade Executante'), ('UNIDADE_SOLICITANTE', 'Unidade Solicitante'), ('EXECUTANTE_SOLICITANTE', 'Executante/Solicitante')], default='UNIDADE_EXECUTANTE', max_length=25),
        ),
    ]
