# Generated by Django 5.2.3 on 2025-06-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_unidadesaude_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='cnes',
            field=models.CharField(blank=True, help_text='Número CNES da Unidade de Saúde', max_length=7, null=True, unique=True),
        ),
    ]
