# Generated by Django 5.2.3 on 2025-06-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_unidadesaude_cnes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesaude',
            name='especialidades',
        ),
    ]
