# Generated by Django 5.2.3 on 2025-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_unidadesaude_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='municipio',
            field=models.CharField(default='Não informado', help_text='Município onde a unidade está localizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='unidadesaude',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
