# Generated by Django 5.2.3 on 2025-06-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_unidadesaude_municipio_alter_unidadesaude_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='usuario_cadastrante',
            field=models.ForeignKey(blank=True, help_text='Usuário que cadastrou esta unidade no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastrante'),
        ),
    ]
