# Generated by Django 5.2.3 on 2025-06-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_usuario_cadastrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesaude',
            name='horario_funcionamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
