# Generated by Django 5.2.3 on 2025-06-27 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_unidadesaude_horario_funcionamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrochamada',
            name='cnes',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código CNES'),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='contato_telefonico_cnes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato Telefônico CNES'),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função/Cargo'),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor de Atuação'),
        ),
        migrations.AddField(
            model_name='registrochamada',
            name='solucao',
            field=models.TextField(blank=True, null=True, verbose_name='Solução/Encaminhamento'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Solicitação'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='nome_atendente',
            field=models.CharField(max_length=255, verbose_name='Nome do Atendente'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='nome_contato',
            field=models.CharField(max_length=255, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='status',
            field=models.CharField(choices=[('chamada_recebida', 'Chamada Recebida'), ('chamada_efetuada', 'Chamada Efetuada')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='tipo_chamada',
            field=models.CharField(choices=[('outro_nao_especificado', 'Outro não especificado'), ('cadastro_profissional', 'Cadastro de profissional'), ('cadastro_unidade', 'Cadastro de Unidade'), ('cancelamento_solicitacao', 'Cancelamento de Solicitacao'), ('capacidade_operacional', 'Capacidade operacional de unidade'), ('contato', 'Contato'), ('contato_medico_regulador', 'Contato com Medico Regulador'), ('fluxo_funcionamento', 'Fluxo de funcionamento do sistema'), ('fluxo_processo_regulacao', 'Fluxo/processo de regulacao'), ('insercao_unidade_perfil', 'Insercao de Unidade em perfil'), ('login_sistema_core', 'Login sistema CORE'), ('manuseio_uso_sistema', 'Manuseio/Uso do sistema'), ('municipio_sem_internet', 'Município sem internet'), ('pactuacao', 'Pactuacao'), ('psiquiatria', 'Psiquiatria'), ('reset_senha_usuario', 'Reset de senha de usuario'), ('sistema_fora_ar', 'Sistema Fora do ar'), ('sistema_lento', 'Sistema Lento'), ('solicitacao_treinamento', 'Solicitacao de treinamento'), ('suporte_ambulatorial', 'Suporte Ambulatorial'), ('suporte_mabulatorial_leitos', 'suporte ao modulo MABULATORIAL E LEITOS'), ('suporte_leitos', 'Suporte Leitos'), ('unidade_sem_internet', 'Unidade sem internet'), ('emergencia', 'Emergência'), ('consulta', 'Consulta'), ('informacao', 'Informação'), ('reclamacao', 'Reclamação'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo de Chamada'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='unidade',
            field=models.CharField(max_length=255, verbose_name='Nome da Unidade'),
        ),
        migrations.AlterField(
            model_name='registrochamada',
            name='usuario_criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador'),
        ),
    ]
