# Generated by Django 5.2.3 on 2025-07-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_unidadesaude_horario_funcionamento_userprofile'),
    ]

    operations = [
    ]
