# Generated by Django 5.2.3 on 2025-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20250706_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='contato_telefonico',
            field=models.CharField(blank=True, help_text='Telefone de contato da unidade', max_length=20, null=True, verbose_name='Contato Telefônico'),
        ),
    ]
